# Generated by Django 4.0.2 on 2022-03-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_feedback_user_stack_profile_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='user',
        ),
    ]
