# Generated by Django 4.0.2 on 2022-03-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
