# Generated by Django 4.0.2 on 2022-03-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='sender_stack',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
