# Generated by Django 4.0.2 on 2022-03-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_profile_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stack',
        ),
        migrations.AddField(
            model_name='stack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
