# Generated by Django 4.0.2 on 2022-03-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='email',
        ),
    ]
