# Generated by Django 4.0.2 on 2022-03-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='stack',
        ),
        migrations.AddField(
            model_name='profile',
            name='stack',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
