# Generated by Django 4.0.2 on 2022-03-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_message_stack_profile_stack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
