# Generated by Django 4.0.2 on 2022-03-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='stack',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
