# Generated by Django 4.0.2 on 2022-03-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_message_stack_profile_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='user',
        ),
    ]
