# Generated by Django 4.0.2 on 2022-03-09 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=976934295, validators=[django.core.validators.MinValueValidator(10000000000), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
